
EXAMPLE=perfbench
CPP_SRC=perfbench.cpp perfbench_serial.cpp
ISPC_SRC=perfbench.ispc
ISPC_FLAGS=--profile
ISPC_IA_TARGETS=sse4-x2 #sse2-i32x4,sse4-i32x4,avx1-i32x8,avx2-i32x8
ISPC_ARM_TARGETS=neon

include ../common_no_task.mk
